
// --- Map & setup ---
const POWERS = [
  { id:"ENG", name:"England", color:"#9400D3", homes:["Lon","Lvp","Edi"] },
  { id:"FRA", name:"France",  color:"#4169E1", homes:["Par","Mar","Bre"] },
  { id:"GER", name:"Germany", color:"#944b07ff", homes:["Kie","Ber","Mun"] },
  { id:"ITA", name:"Italy",   color:"#228B22", homes:["Ven","Rom","Nap"] },
  { id:"AUS", name:"Austria", color:"#da3919ff", homes:["Vie","Bud","Tri"] },
  { id:"RUS", name:"Russia",  color:"#8d8e91ff", homes:["War","Mos","StP","Sev"] },
  { id:"TUR", name:"Turkey",  color:"#b9a61c", homes:["Con","Smy","Ank"] },
];
const byPower = id => POWERS.find(p=>p.id===id);

const PROVINCES = {
  "Adr": {name:"Adriatic Sea", type:"sea", x:793.5, y:1048.0, adj:["Ion","Apu","Ven","Tri","Alb"]},
  "Aeg": {name:"Aegean Sea", type:"sea", x:1043.5, y:1230.0, adj:["Ion","Eas","Gre","Bul-sc","Bul","Con","Smy"]},
  "Alb": {name:"Albania", type:"land", coast:true, sc:false, x:906.5, y:1113.0, adj:[/*...*/]},
  "Ank": {name:"Ankara", type:"land", coast:true, sc:true, x:1301.5, y:1110.0, adj:[/*...*/]},
  "Apu": {name:"Apulia", type:"land", coast:true, sc:false, x:791.5, y:1106.0, adj:[/*...*/]},
  "Arm": {name:"Armenia", type:"land", coast:true, sc:false, x:1484.5, y:1090.0, adj:[/*...*/]},
  "Bal": {name:"Baltic Sea", type:"sea", x:878.5, y:610.0, adj:[/*...*/]},
  "Bar": {name:"Barents Sea", type:"sea", x:1162.5, y:73.0, adj:[/*...*/]},
  "Bel": {name:"Belgium", type:"land", coast:true, sc:true, x:561.5, y:753.0, adj:[/*...*/]},
  "Ber": {name:"Berlin", type:"land", coast:true, sc:true, x:771.5, y:690.0, adj:[/*...*/]},
  "Bla": {name:"Black Sea", type:"sea", x:1233.5, y:1000.0, adj:[/*...*/]},
  "Boh": {name:"Bohemia", type:"land", coast:false, sc:false, x:806.5, y:814.0, adj:[/*...*/]},
  "Bot": {name:"Gulf of Bothnia", type:"sea", x:941.5, y:485.0, adj:[/*...*/]},
  "Bre": {name:"Brest", type:"land", coast:true, sc:true, x:404.5, y:819.0, adj:[/*...*/]},
  "Bud": {name:"Budapest", type:"land", coast:false, sc:true, x:950.5, y:904.0, adj:[/*...*/]},
  "Bul": {name:"Bulgaria", type:"land", coast:true, sc:true, x:1048.5, y:1068.0, adj:[/*...*/]},
  "Bul-ec": {name:"Bulgaria (East Coast)", type:"land", coast:true, sc:true, x:1127.0, y:1067.0, adj:[/*...*/]},
  "Bul-sc": {name:"Bulgaria (South Coast)", type:"land", coast:true, sc:true, x:1070.0, y:1140.0, adj:[/*...*/]},
  "Bur": {name:"Burgundy", type:"land", coast:false, sc:false, x:559.5, y:871.0, adj:[/*...*/]},
  "Cly": {name:"Clyde", type:"land", coast:true, sc:false, x:436.5, y:492.0, adj:[/*...*/]},
  "Con": {name:"Constantinople", type:"land", coast:true, sc:true, x:1145.5, y:1137.0, adj:[/*...*/]},
  "Den": {name:"Denmark", type:"land", coast:true, sc:true, x:703.5, y:587.0, adj:[/*...*/]},
  "Eas": {name:"Eastern Mediterranean", type:"sea", x:1218.5, y:1311.0, adj:[/*...*/]},
  "Edi": {name:"Edinburgh", type:"land", coast:true, sc:true, x:473.5, y:514.0, adj:["Nwg","Nth","Cly","Lvp","Yor"]},
  "Eng": {name:"English Channel", type:"sea", x:394.5, y:751.0, adj:[/*...*/]},
  "Fin": {name:"Finland", type:"land", coast:true, sc:false, x:988.5, y:380.0, adj:[/*...*/]},
  "Gal": {name:"Galicia", type:"land", coast:false, sc:false, x:999.5, y:831.0, adj:[/*...*/]},
  "Gas": {name:"Gascony", type:"land", coast:true, sc:false, x:422.5, y:912.0, adj:[/*...*/]},
  "GoL": {name:"Gulf of Lyon", type:"sea", x:556.0, y:1060.0, adj:[/*...*/]},
  "Gre": {name:"Greece", type:"land", coast:true, sc:true, x:966.5, y:1190.0, adj:[/*...*/]},
  "Hel": {name:"Helgoland Bight", type:"sea", x:651.5, y:631.0, adj:[/*...*/]},
  "Hol": {name:"Holland", type:"land", coast:true, sc:true, x:596.5, y:711.0, adj:[/*...*/]},
  "Ion": {name:"Ionian Sea", type:"sea", x:846.5, y:1286.0, adj:[/*...*/]},
  "Iri": {name:"Irish Sea", type:"sea", x:335.5, y:661.0, adj:[/*...*/]},
  "Kie": {name:"Kiel", type:"land", coast:true, sc:true, x:683.5, y:701.0, adj:[/*...*/]},
  "Lon": {name:"London", type:"land", coast:true, sc:true, x:488.5, y:675.0, adj:[/*...*/]},
  "Lvn": {name:"Livonia", type:"land", coast:true, sc:false, x:1025.5, y:567.0, adj:[/*...*/]},
  "Lvp": {name:"Liverpool", type:"land", coast:true, sc:true, x:450.5, y:576.0, adj:[/*...*/]},
  "Lyo": {name:"Gulf of Lyon", type:"sea", x:514.3, y:1055.0, adj:[/*...*/]},
  "MAO": {name:"Mid-Atlantic", type:"sea", x:141.8, y:835.3, adj:[/*...*/]},
  "Mar": {name:"Marseilles", type:"land", coast:true, sc:true, x:524.5, y:975.0, adj:[/*...*/]},
  "Mid": {name:"Mid-Atlantic", type:"sea", x:126.0, y:902.0, adj:[/*...*/]},
  "Mos": {name:"Moscow", type:"land", coast:false, sc:true, x:1200.5, y:590.0, adj:[/*...*/]},
  "Mun": {name:"Munich", type:"land", coast:false, sc:true, x:693.5, y:828.0, adj:[/*...*/]},
  "NAf": {name:"North Africa", type:"land", coast:true, sc:false, x:325.5, y:1281.0, adj:[/*...*/]},
  "NAO": {name:"North Atlantic", type:"sea", x:180.1, y:288.2, adj:["Nwg","Iri","MAO","Cly","Lvp"]},
  "Nap": {name:"Naples", type:"land", coast:true, sc:true, x:806.5, y:1170.0, adj:[/*...*/]},
  "Nat": {name:"North Atlantic", type:"sea", x:238.0, y:427.0, adj:[/*...*/]},
  "Nrg": {name:"Norwegian Sea", type:"sea", x:605.0, y:250.0, adj:[/*...*/]},
  "Nth": {name:"North Sea", type:"sea", x:553.5, y:560.0, adj:[/*...*/]},
  "Nwg": {name:"Norwegian Sea", type:"sea", x:652.7, y:181.8, adj:[/*...*/]},
  "Nwy": {name:"Norway", type:"land", coast:true, sc:true, x:703.5, y:410.0, adj:[/*...*/]},
  "Par": {name:"Paris", type:"land", coast:false, sc:true, x:488.5, y:845.0, adj:[/*...*/]},
  "Pic": {name:"Picardy", type:"land", coast:true, sc:false, x:523.5, y:781.0, adj:[/*...*/]},
  "Pie": {name:"Piedmont", type:"land", coast:true, sc:false, x:630.5, y:968.0, adj:[/*...*/]},
  "Por": {name:"Portugal", type:"land", coast:true, sc:true, x:181.5, y:1013.0, adj:[/*...*/]},
  "Pru": {name:"Prussia", type:"land", coast:true, sc:false, x:865.5, y:690.0, adj:[/*...*/]},
  "Rom": {name:"Rome", type:"land", coast:true, sc:true, x:731.5, y:1102.0, adj:[/*...*/]},
  "Ruh": {name:"Ruhr", type:"land", coast:false, sc:false, x:636.5, y:779.0, adj:[/*...*/]},
  "Rum": {name:"Rumania", type:"land", coast:true, sc:true, x:1096.5, y:967.0, adj:[/*...*/]},
  "Ser": {name:"Serbia", type:"land", coast:false, sc:true, x:933.5, y:1050.0, adj:[/*...*/]},
  "Sev": {name:"Sevastopol", type:"land", coast:true, sc:true, x:1284.5, y:845.0, adj:[/*...*/]},
  "Sil": {name:"Silesia", type:"land", coast:false, sc:false, x:832.5, y:769.0, adj:[/*...*/]},
  "Ska": {name:"Skagerrak", type:"sea", x:735.5, y:518.0, adj:[/*...*/]},
  "Smy": {name:"Smyrna", type:"land", coast:true, sc:true, x:1253.5, y:1210.0, adj:[/*...*/]},
  "Spa": {name:"Spain", type:"land", coast:true, sc:true, x:335.5, y:1039.0, adj:[/*...*/]},
  "Spa-nc": {name:"Spain (North Coast)", type:"land", coast:true, sc:true, x:289.0, y:965.0, adj:[/*...*/]},
  "Spa-sc": {name:"Spain (South Coast)", type:"land", coast:true, sc:true, x:291.0, y:1166.0, adj:[/*...*/]},
  "StP": {name:"St Petersburg", type:"land", coast:true, sc:true, x:1166.5, y:405.0, adj:[/*...*/]},
  "StP-nc": {name:"St Petersburg (North Coast)", type:"land", coast:true, sc:true, x:1218.0, y:222.0, adj:[/*...*/]},
  "StP-sc": {name:"St Petersburg (South Coast)", type:"land", coast:true, sc:true, x:1066.0, y:487.0, adj:[/*...*/]},
  "Swe": {name:"Sweden", type:"land", coast:true, sc:true, x:829.5, y:459.0, adj:[/*...*/]},
  "Swi": {name:"Switzerland", type:"land", coast:false, sc:false, x:642.0, y:928.0, adj:[/*...*/]},
  "Syr": {name:"Syria", type:"land", coast:true, sc:false, x:1452.5, y:1206.0, adj:[/*...*/]},
  "Tri": {name:"Trieste", type:"land", coast:true, sc:true, x:825.5, y:996.0, adj:[/*...*/]},
  "Tun": {name:"Tunis", type:"land", coast:true, sc:true, x:622.5, y:1300.0, adj:[/*...*/]},
  "Tus": {name:"Tuscany", type:"land", coast:true, sc:false, x:686.5, y:1034.0, adj:[/*...*/]},
  "Tyn": {name:"Tyrrhenian Sea", type:"sea", x:720.0, y:1160.0, adj:[/*...*/]},
  "Tyr": {name:"Tyrolia", type:"land", coast:false, sc:false, x:742.5, y:904.0, adj:[/*...*/]},
  "Tys": {name:"Tyrrhenian Sea", type:"sea", x:698.5, y:1149.1, adj:[/*...*/]},
  "Ukr": {name:"Ukraine", type:"land", coast:false, sc:false, x:1124.5, y:800.0, adj:[/*...*/]},
  "Ven": {name:"Venice", type:"land", coast:true, sc:true, x:707.5, y:994.0, adj:[/*...*/]},
  "Vie": {name:"Vienna", type:"land", coast:false, sc:true, x:855.5, y:864.0, adj:[/*...*/]},
  "Wal": {name:"Wales", type:"land", coast:true, sc:false, x:428.5, y:658.0, adj:[/*...*/]},
  "War": {name:"Warsaw", type:"land", coast:false, sc:true, x:983.5, y:740.0, adj:[/*...*/]},
  "Wes": {name:"Western Mediterranean", type:"sea", x:462.5, y:1163.0, adj:[/*...*/]},
  "Yor": {name:"Yorkshire", type:"land", coast:true, sc:false, x:492.5, y:616.0, adj:[/*...*/]}
};


// Starting units & ownership
let START_UNITS = [
  { id:"ENG_F_Edi", power:"ENG", kind:"F", prov:"Edi" },
  { id:"ENG_A_Lvp", power:"ENG", kind:"A", prov:"Lvp" },
  { id:"ENG_F_Lon", power:"ENG", kind:"F", prov:"Lon" },
  { id:"FRA_A_Par", power:"FRA", kind:"A", prov:"Par" },
  { id:"FRA_A_Mar", power:"FRA", kind:"A", prov:"Mar" },
  { id:"FRA_F_Bre", power:"FRA", kind:"F", prov:"Bre" },
  { id:"GER_A_Ber", power:"GER", kind:"A", prov:"Ber" },
  { id:"GER_A_Mun", power:"GER", kind:"A", prov:"Mun" },
  { id:"GER_F_Kie", power:"GER", kind:"F", prov:"Kie" },
  { id:"ITA_A_Rom", power:"ITA", kind:"A", prov:"Rom" },
  { id:"ITA_A_Ven", power:"ITA", kind:"A", prov:"Ven" },
  { id:"ITA_F_Nap", power:"ITA", kind:"F", prov:"Nap" },
  { id:"AUS_A_Vie", power:"AUS", kind:"A", prov:"Vie" },
  { id:"AUS_A_Bud", power:"AUS", kind:"A", prov:"Bud" },
  { id:"AUS_F_Tri", power:"AUS", kind:"F", prov:"Tri" },
  { id:"RUS_A_War", power:"RUS", kind:"A", prov:"War" },
  { id:"RUS_A_Mos", power:"RUS", kind:"A", prov:"Mos" },
  { id:"RUS_F_Sev", power:"RUS", kind:"F", prov:"Sev" },
  { id:"RUS_F_StP", power:"RUS", kind:"F", prov:"StP" },
  { id:"TUR_A_Con", power:"TUR", kind:"A", prov:"Con" },
  { id:"TUR_A_Smy", power:"TUR", kind:"A", prov:"Smy" },
  { id:"TUR_F_Ank", power:"TUR", kind:"F", prov:"Ank" },
];
let START_OWNERSHIP = {}; POWERS.forEach(p=> p.homes.forEach(h=> START_OWNERSHIP[h] = p.id));

// Export to window to avoid undefined in guards
window.POWERS = POWERS; window.PROVINCES = PROVINCES; window.START_UNITS = START_UNITS; window.START_OWNERSHIP = START_OWNERSHIP; window.byPower = byPower;
